[package]
name = "exercise3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.5.0"
serde = {version = "1.0.152", features = ["serde_derive"]}
serde_with = "2.2.0"
